server:
  port: 8080

spring:
  datasource:
    url: jdbc:mariadb://127.0.0.1:8989/test
    driver-class-name: org.mariadb.jdbc.Driver
    username: root
    password: password
  

#配置mybatis相关文件路径
mybatis:
  #映射配置文件路径
  mapper-locations: classpath:mybatis/mapper/*.xml
  #核心配置文件路径
  config-location: classpath:mybatis/mybatis-config.xml
  
token:
  key: KJHUhjjJYgYUllVbXhKDHXhkSyHjlNiVkYzWTBac1Yxkjhuad
  vaildTime: 120